[2024-09-30T19:50:07.745+0000] {processor.py:156} INFO - Started process (PID=58) to work on /opt/airflow/dags/etl_posts_comments.py
[2024-09-30T19:50:07.746+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/etl_posts_comments.py for tasks to queue
[2024-09-30T19:50:07.747+0000] {logging_mixin.py:149} INFO - [2024-09-30T19:50:07.747+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl_posts_comments.py
[2024-09-30T19:50:08.935+0000] {logging_mixin.py:149} INFO - [2024-09-30T19:50:08.934+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_posts_comments.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_posts_comments.py", line 17, in <module>
    from Senior_Data_Analyst_Challenge.ingestion_incremental.ingestion_inicial import main
ModuleNotFoundError: No module named 'Senior_Data_Analyst_Challenge'
[2024-09-30T19:50:08.936+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_posts_comments.py
[2024-09-30T19:50:08.965+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/etl_posts_comments.py took 1.223 seconds
[2024-09-30T19:50:40.146+0000] {processor.py:156} INFO - Started process (PID=118) to work on /opt/airflow/dags/etl_posts_comments.py
[2024-09-30T19:50:40.148+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/etl_posts_comments.py for tasks to queue
[2024-09-30T19:50:40.153+0000] {logging_mixin.py:149} INFO - [2024-09-30T19:50:40.152+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl_posts_comments.py
[2024-09-30T19:50:42.626+0000] {logging_mixin.py:149} INFO - [2024-09-30T19:50:42.622+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_posts_comments.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_posts_comments.py", line 17, in <module>
    from Senior_Data_Analyst_Challenge.ingestion_incremental.ingestion_inicial import main
ModuleNotFoundError: No module named 'Senior_Data_Analyst_Challenge'
[2024-09-30T19:50:42.626+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_posts_comments.py
[2024-09-30T19:50:42.689+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/etl_posts_comments.py took 2.563 seconds
